-- 1. Tabel Peserta REHAB
CREATE TABLE IF NOT EXISTS patients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  phone_number TEXT NOT NULL,
  card_number TEXT NOT NULL,
  installment_amount NUMERIC NOT NULL DEFAULT 0,
  due_date DATE NOT NULL,
  notes TEXT,
  status TEXT DEFAULT 'Aktif',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Tabel Template Pesan WhatsApp
CREATE TABLE IF NOT EXISTS templates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  is_default BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Insert Default Template jika belum ada
INSERT INTO templates (title, content, is_default)
SELECT 'Pesan Penagihan Standar', 'Halo Bpk/Ibu *{nama}*,\n\nKami menginfokan bahwa cicilan program REHAB BPJS Kesehatan untuk Nomor Kartu JKN *{nomor_peserta}* sebesar *{nominal}* akan jatuh tempo pada tanggal *{tanggal_jatuh_tempo}*.\n\nMohon dapat melakukan pembayaran tepat waktu demi kelancaran kepesertaan Anda. Terima kasih.', TRUE
WHERE NOT EXISTS (SELECT 1 FROM templates WHERE is_default = TRUE);

-- 3. Tabel Riwayat Reminder
CREATE TABLE IF NOT EXISTS reminder_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id BIGINT REFERENCES patients(id) ON DELETE SET NULL,
  patient_name TEXT NOT NULL,
  phone_number TEXT NOT NULL,
  template_title TEXT,
  message_content TEXT NOT NULL,
  status TEXT DEFAULT 'Dibuka', -- Status: 'Dibuka' atau 'Terkirim'
  sent_at TIMESTAMPTZ DEFAULT NOW(),
  confirmed_at TIMESTAMPTZ
);

-- 4. Tabel Pengaturan Sistem
CREATE TABLE IF NOT EXISTS settings (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL
);

-- Insert Default Settings
INSERT INTO settings (key, value) VALUES ('default_delay', '15') ON CONFLICT (key) DO NOTHING;
INSERT INTO settings (key, value) VALUES ('default_template_id', '1') ON CONFLICT (key) DO NOTHING;